-- Podstream v0.1.1
-- Logical isolation inside the shared personal Supabase project.
-- All Podstream tables use a podstream_ prefix and RLS ownership policies.

create table if not exists public.podstream_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feed_url text not null,
  title text,
  image_url text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, feed_url)
);

create table if not exists public.podstream_playback_positions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  episode_id text not null,
  position_seconds double precision not null default 0 check (position_seconds >= 0),
  duration_seconds double precision not null default 0 check (duration_seconds >= 0),
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (user_id, episode_id)
);

create table if not exists public.podstream_stars (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null check (item_type in ('episode','show')),
  item_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, item_type, item_id)
);

create table if not exists public.podstream_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enhance_voices boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.podstream_subscriptions enable row level security;
alter table public.podstream_playback_positions enable row level security;
alter table public.podstream_stars enable row level security;
alter table public.podstream_settings enable row level security;

revoke all on table public.podstream_subscriptions from anon, authenticated;
revoke all on table public.podstream_playback_positions from anon, authenticated;
revoke all on table public.podstream_stars from anon, authenticated;
revoke all on table public.podstream_settings from anon, authenticated;

grant select, insert, update, delete on table public.podstream_subscriptions to authenticated;
grant select, insert, update, delete on table public.podstream_playback_positions to authenticated;
grant select, insert, update, delete on table public.podstream_stars to authenticated;
grant select, insert, update, delete on table public.podstream_settings to authenticated;
grant usage, select on sequence public.podstream_subscriptions_id_seq to authenticated;
grant usage, select on sequence public.podstream_playback_positions_id_seq to authenticated;
grant usage, select on sequence public.podstream_stars_id_seq to authenticated;

create policy "Podstream users read own subscriptions" on public.podstream_subscriptions
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Podstream users insert own subscriptions" on public.podstream_subscriptions
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Podstream users update own subscriptions" on public.podstream_subscriptions
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Podstream users delete own subscriptions" on public.podstream_subscriptions
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Podstream users read own playback" on public.podstream_playback_positions
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Podstream users insert own playback" on public.podstream_playback_positions
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Podstream users update own playback" on public.podstream_playback_positions
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Podstream users delete own playback" on public.podstream_playback_positions
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Podstream users read own stars" on public.podstream_stars
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Podstream users insert own stars" on public.podstream_stars
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Podstream users update own stars" on public.podstream_stars
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Podstream users delete own stars" on public.podstream_stars
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Podstream users read own settings" on public.podstream_settings
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Podstream users insert own settings" on public.podstream_settings
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Podstream users update own settings" on public.podstream_settings
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Podstream users delete own settings" on public.podstream_settings
  for delete to authenticated using ((select auth.uid()) = user_id);

-- v0.2.6: persistent per-user episode archive. Episodes are retained even
-- when a publisher later shortens the current RSS feed.
create table if not exists public.podstream_episode_archive (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  episode_id text not null,
  show_id text not null,
  feed_url text,
  show_title text,
  title text,
  audio_url text not null,
  published_at timestamptz,
  duration_seconds double precision not null default 0 check (duration_seconds >= 0),
  image_url text,
  source text not null default 'rss',
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, episode_id)
);

alter table public.podstream_episode_archive enable row level security;
revoke all on table public.podstream_episode_archive from anon, authenticated;
grant select, insert, update, delete on table public.podstream_episode_archive to authenticated;
grant usage, select on sequence public.podstream_episode_archive_id_seq to authenticated;

create policy "Podstream users read own episode archive" on public.podstream_episode_archive
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Podstream users insert own episode archive" on public.podstream_episode_archive
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Podstream users update own episode archive" on public.podstream_episode_archive
  for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Podstream users delete own episode archive" on public.podstream_episode_archive
  for delete to authenticated using ((select auth.uid()) = user_id);

create index if not exists podstream_episode_archive_user_show_idx
  on public.podstream_episode_archive (user_id, show_id);
create index if not exists podstream_episode_archive_user_published_idx
  on public.podstream_episode_archive (user_id, published_at desc);

alter table public.podstream_subscriptions add column if not exists catalog_total integer;
alter table public.podstream_subscriptions add column if not exists backfilled_at timestamptz;
