-- Podstream v0.1.0
-- Run this in Supabase SQL Editor.

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  feed_url text not null,
  title text,
  image_url text,
  created_at timestamptz not null default now(),
  unique(user_id, feed_url)
);

create table if not exists public.playback_positions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  episode_id text not null,
  position_seconds double precision not null default 0,
  duration_seconds double precision not null default 0,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(user_id, episode_id)
);

create table if not exists public.stars (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null check (item_type in ('episode','show')),
  item_id text not null,
  created_at timestamptz not null default now(),
  unique(user_id, item_type, item_id)
);

alter table public.subscriptions enable row level security;
alter table public.playback_positions enable row level security;
alter table public.stars enable row level security;

create policy "Users manage own subscriptions" on public.subscriptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own playback" on public.playback_positions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own stars" on public.stars
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
